version: '3.8'
services:
 db: 
   build: ./db  
   container_name: archive-db
   ports:     
    - "5432:5432" 
   environment: 
    - POSTGRES_USER=postgres  
    - POSTGRES_PASSWORD=postgres 
    - POSTGRES_DB=archive
   volumes:
   - ./data:/data
networks:
  default:
    name: archive_net
  # api:
  #   container_name: archive-api
  #   build:
  #     context: ./
  #     target: production
  #   image: archive-api
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   environment:
  #     NODE_ENV: production
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: postgres
  #   links:
  #     - db
  #   volumes:
  #     - './:/src'